spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  servlet:
    multipart:
      max-file-size: 2MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-abka0tkf5ulo1yrc.us.auth0.com/
          jwk-set-uri: https://dev-abka0tkf5ulo1yrc.us.auth0.com/.well-known/jwks.json
#          audiences:

virtual-arena:
  auth:
    access-token:
      subject: email
  storage:
    cloudinary:
      cloud-name: ${CLOUDINARY_CLOUD_NAME}
      api-key: ${CLOUDINARY_API_KEY}
      api-secret: ${CLOUDINARY_API_SECRET}
